//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZapTranslation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZapTranslation.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoalignment Images.
        /// </summary>
        internal static string AAImages {
            get {
                return ResourceManager.GetString("AAImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction {0} from {1} at {2}.
        /// </summary>
        internal static string AAImagesCaption {
            get {
                return ResourceManager.GetString("AAImagesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string Alignment {
            get {
                return ResourceManager.GetString("Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axial.
        /// </summary>
        internal static string AxialDegrees {
            get {
                return ResourceManager.GetString("AxialDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams.
        /// </summary>
        internal static string Beams {
            get {
                return ResourceManager.GetString("Beams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        internal static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CI.
        /// </summary>
        internal static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening ZapClient.
        /// </summary>
        internal static string ClientOpenErrorCaption {
            get {
                return ResourceManager.GetString("ClientOpenErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open ZapClient for server {0} on port {1} for user &apos;{2}&apos;.
        /// </summary>
        internal static string ClientOpenErrorText {
            get {
                return ResourceManager.GetString("ClientOpenErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collimator.
        /// </summary>
        internal static string Collimator {
            get {
                return ResourceManager.GetString("Collimator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Point Dose is defined as the dose, which a volume of 35 mm³ is getting.
        /// </summary>
        internal static string CommentPointDose {
            get {
                return ResourceManager.GetString("CommentPointDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commisioned.
        /// </summary>
        internal static string Commisioned {
            get {
                return ResourceManager.GetString("Commisioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contours.
        /// </summary>
        internal static string Contours {
            get {
                return ResourceManager.GetString("Contours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coverage.
        /// </summary>
        internal static string Coverage {
            get {
                return ResourceManager.GetString("Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT Density Model.
        /// </summary>
        internal static string CTDensityModel {
            get {
                return ResourceManager.GetString("CTDensityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT value.
        /// </summary>
        internal static string CTValue {
            get {
                return ResourceManager.GetString("CTValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Beams.
        /// </summary>
        internal static string DeliveredBeams {
            get {
                return ResourceManager.GetString("DeliveredBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        internal static string DeliveredMU {
            get {
                return ResourceManager.GetString("DeliveredMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MV MU.
        /// </summary>
        internal static string DeliveredMUFromMV {
            get {
                return ResourceManager.GetString("DeliveredMUFromMV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Time.
        /// </summary>
        internal static string DeliveredTime {
            get {
                return ResourceManager.GetString("DeliveredTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Report.
        /// </summary>
        internal static string DeliveryReport {
            get {
                return ResourceManager.GetString("DeliveryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        internal static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density Model.
        /// </summary>
        internal static string DensityModel {
            get {
                return ResourceManager.GetString("DensityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose.
        /// </summary>
        internal static string Dose {
            get {
                return ResourceManager.GetString("Dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose.
        /// </summary>
        internal static string DoseInMicroGy {
            get {
                return ResourceManager.GetString("DoseInMicroGy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose Volume Histograms.
        /// </summary>
        internal static string DoseVolumeHistograms {
            get {
                return ResourceManager.GetString("DoseVolumeHistograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry run.
        /// </summary>
        internal static string DryRun {
            get {
                return ResourceManager.GetString("DryRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVHs.
        /// </summary>
        internal static string DVHs {
            get {
                return ResourceManager.GetString("DVHs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DV Spacing.
        /// </summary>
        internal static string DVSpacing {
            get {
                return ResourceManager.GetString("DVSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFoundErrorCaption {
            get {
                return ResourceManager.GetString("FileNotFoundErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find file &apos;{0}&apos;.
        /// </summary>
        internal static string FileNotFoundErrorText {
            get {
                return ResourceManager.GetString("FileNotFoundErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction.
        /// </summary>
        internal static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string FractionEnd {
            get {
                return ResourceManager.GetString("FractionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction.
        /// </summary>
        internal static string FractionId {
            get {
                return ResourceManager.GetString("FractionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction.
        /// </summary>
        internal static string FractionMU {
            get {
                return ResourceManager.GetString("FractionMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractions.
        /// </summary>
        internal static string Fractions {
            get {
                return ResourceManager.GetString("Fractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string FractionsAll {
            get {
                return ResourceManager.GetString("FractionsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string FractionStart {
            get {
                return ResourceManager.GetString("FractionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction Summary.
        /// </summary>
        internal static string FractionSummary {
            get {
                return ResourceManager.GetString("FractionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string FractionTotal {
            get {
                return ResourceManager.GetString("FractionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From dose cube.
        /// </summary>
        internal static string FromDoseVolume {
            get {
                return ResourceManager.GetString("FromDoseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From structure.
        /// </summary>
        internal static string FromStructureBrain {
            get {
                return ResourceManager.GetString("FromStructureBrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gantry.
        /// </summary>
        internal static string GantryTime {
            get {
                return ResourceManager.GetString("GantryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GI.
        /// </summary>
        internal static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose [cGy].
        /// </summary>
        internal static string GraphicsDose {
            get {
                return ResourceManager.GetString("GraphicsDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraphicsVolume.
        /// </summary>
        internal static string GraphicsVolume {
            get {
                return ResourceManager.GetString("GraphicsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired.
        /// </summary>
        internal static string ImageAquired {
            get {
                return ResourceManager.GetString("ImageAquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageTime {
            get {
                return ResourceManager.GetString("ImageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indices.
        /// </summary>
        internal static string Indices {
            get {
                return ResourceManager.GetString("Indices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        internal static string InitTime {
            get {
                return ResourceManager.GetString("InitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isocenter.
        /// </summary>
        internal static string IsocenterId {
            get {
                return ResourceManager.GetString("IsocenterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isocenters.
        /// </summary>
        internal static string Isocenters {
            get {
                return ResourceManager.GetString("Isocenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kV Image.
        /// </summary>
        internal static string kVImage {
            get {
                return ResourceManager.GetString("kVImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kV Images.
        /// </summary>
        internal static string kVImages {
            get {
                return ResourceManager.GetString("kVImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary kV images.
        /// </summary>
        internal static string kVImagesShort {
            get {
                return ResourceManager.GetString("kVImagesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINAC Energy.
        /// </summary>
        internal static string LINACEnergy {
            get {
                return ResourceManager.GetString("LINACEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 MV.
        /// </summary>
        internal static string LINACEnergyText {
            get {
                return ResourceManager.GetString("LINACEnergyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linac.
        /// </summary>
        internal static string LinacTime {
            get {
                return ResourceManager.GetString("LinacTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string M {
            get {
                return ResourceManager.GetString("M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makeup Fraction.
        /// </summary>
        internal static string Makeup_Fraction {
            get {
                return ResourceManager.GetString("Makeup Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max [cGy].
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max dose.
        /// </summary>
        internal static string MaxDose {
            get {
                return ResourceManager.GetString("MaxDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum dose.
        /// </summary>
        internal static string MaximumDose {
            get {
                return ResourceManager.GetString("MaximumDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Dose.
        /// </summary>
        internal static string MaxPointDose {
            get {
                return ResourceManager.GetString("MaxPointDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean [cGy].
        /// </summary>
        internal static string Mean {
            get {
                return ResourceManager.GetString("Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean dose.
        /// </summary>
        internal static string MeanDose {
            get {
                return ResourceManager.GetString("MeanDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Id.
        /// </summary>
        internal static string MedicalId {
            get {
                return ResourceManager.GetString("MedicalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min [cGy].
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min dose.
        /// </summary>
        internal static string MinDose {
            get {
                return ResourceManager.GetString("MinDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most common parameters for kV images.
        /// </summary>
        internal static string MostCommonParameter {
            get {
                return ResourceManager.GetString("MostCommonParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MU.
        /// </summary>
        internal static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUs per fraction.
        /// </summary>
        internal static string MUPerFraction {
            get {
                return ResourceManager.GetString("MUPerFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nCI.
        /// </summary>
        internal static string nCI {
            get {
                return ResourceManager.GetString("nCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string NodeId {
            get {
                return ResourceManager.GetString("NodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beams.
        /// </summary>
        internal static string NonZeroBeams {
            get {
                return ResourceManager.GetString("NonZeroBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of beams.
        /// </summary>
        internal static string NumOfBeams {
            get {
                return ResourceManager.GetString("NumOfBeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of fractions.
        /// </summary>
        internal static string NumOfFractions {
            get {
                return ResourceManager.GetString("NumOfFractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of isocenters.
        /// </summary>
        internal static string NumOfIsocenters {
            get {
                return ResourceManager.GetString("NumOfIsocenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblique.
        /// </summary>
        internal static string ObliqueDegrees {
            get {
                return ResourceManager.GetString("ObliqueDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information.
        /// </summary>
        internal static string PatientHeader {
            get {
                return ResourceManager.GetString("PatientHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient information.
        /// </summary>
        internal static string PatientInformation {
            get {
                return ResourceManager.GetString("PatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient name.
        /// </summary>
        internal static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAP-X TPS.
        /// </summary>
        internal static string PDFCreator {
            get {
                return ResourceManager.GetString("PDFCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZapPlanReport.
        /// </summary>
        internal static string PDFProducer {
            get {
                return ResourceManager.GetString("PDFProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAP Report.
        /// </summary>
        internal static string PDFSubjectPlan {
            get {
                return ResourceManager.GetString("PDFSubjectPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Report.
        /// </summary>
        internal static string PDFSubjectTreatment {
            get {
                return ResourceManager.GetString("PDFSubjectTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string PDFTitle {
            get {
                return ResourceManager.GetString("PDFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        internal static string Physician {
            get {
                return ResourceManager.GetString("Physician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physicist.
        /// </summary>
        internal static string Physicist {
            get {
                return ResourceManager.GetString("Physicist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Compare.
        /// </summary>
        internal static string PlanCompare {
            get {
                return ResourceManager.GetString("PlanCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan information.
        /// </summary>
        internal static string PlanInformation {
            get {
                return ResourceManager.GetString("PlanInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string PlanMU {
            get {
                return ResourceManager.GetString("PlanMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planname.
        /// </summary>
        internal static string Planname {
            get {
                return ResourceManager.GetString("Planname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plannames.
        /// </summary>
        internal static string Plannames {
            get {
                return ResourceManager.GetString("Plannames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning Report.
        /// </summary>
        internal static string PlanningReport {
            get {
                return ResourceManager.GetString("PlanningReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Report.
        /// </summary>
        internal static string PlanReport {
            get {
                return ResourceManager.GetString("PlanReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Planning Report.
        /// </summary>
        internal static string PlanReportTitle {
            get {
                return ResourceManager.GetString("PlanReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plans.
        /// </summary>
        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed dose [cGy].
        /// </summary>
        internal static string PrescribedDose {
            get {
                return ResourceManager.GetString("PrescribedDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescribed isodose.
        /// </summary>
        internal static string PrescribedIsodose {
            get {
                return ResourceManager.GetString("PrescribedIsodose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription dose.
        /// </summary>
        internal static string PrescriptionDose {
            get {
                return ResourceManager.GetString("PrescriptionDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription isodose.
        /// </summary>
        internal static string PrescriptionIsodose {
            get {
                return ResourceManager.GetString("PrescriptionIsodose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary series.
        /// </summary>
        internal static string PrimarySeries {
            get {
                return ResourceManager.GetString("PrimarySeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create PDF.
        /// </summary>
        internal static string PrintPDF {
            get {
                return ResourceManager.GetString("PrintPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string ProcessingTime {
            get {
                return ResourceManager.GetString("ProcessingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generator.
        /// </summary>
        internal static string ReportGenerator {
            get {
                return ResourceManager.GetString("ReportGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved date.
        /// </summary>
        internal static string SavedDate {
            get {
                return ResourceManager.GetString("SavedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary series.
        /// </summary>
        internal static string SecondarySeries {
            get {
                return ResourceManager.GetString("SecondarySeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string SetupTime {
            get {
                return ResourceManager.GetString("SetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signs.
        /// </summary>
        internal static string Signs {
            get {
                return ResourceManager.GetString("Signs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        internal static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        internal static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        internal static string Structures {
            get {
                return ResourceManager.GetString("Structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All PTVs.
        /// </summary>
        internal static string SumOfPTVs {
            get {
                return ResourceManager.GetString("SumOfPTVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System information.
        /// </summary>
        internal static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZAP-X - {0}.
        /// </summary>
        internal static string SystemText {
            get {
                return ResourceManager.GetString("SystemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TableTime {
            get {
                return ResourceManager.GetString("TableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing Details.
        /// </summary>
        internal static string TimingDetails {
            get {
                return ResourceManager.GetString("TimingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total kV Dose.
        /// </summary>
        internal static string TotalkVDose {
            get {
                return ResourceManager.GetString("TotalkVDose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total kV images.
        /// </summary>
        internal static string TotalkVImages {
            get {
                return ResourceManager.GetString("TotalkVImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of which used for AA.
        /// </summary>
        internal static string TotalkVImagesForAA {
            get {
                return ResourceManager.GetString("TotalkVImagesForAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of which used for AA and TA.
        /// </summary>
        internal static string TotalkVImagesForAAandTA {
            get {
                return ResourceManager.GetString("TotalkVImagesForAAandTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of which used for in treatment.
        /// </summary>
        internal static string TotalkVImagesForInTreatment {
            get {
                return ResourceManager.GetString("TotalkVImagesForInTreatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of which used for TA.
        /// </summary>
        internal static string TotalkVImagesForTA {
            get {
                return ResourceManager.GetString("TotalkVImagesForTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total MUs.
        /// </summary>
        internal static string TotalMU {
            get {
                return ResourceManager.GetString("TotalMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPS Version.
        /// </summary>
        internal static string TPSVersion {
            get {
                return ResourceManager.GetString("TPSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Delivery Report.
        /// </summary>
        internal static string TreatmentDeliveryReport {
            get {
                return ResourceManager.GetString("TreatmentDeliveryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Planning Report.
        /// </summary>
        internal static string TreatmentPlanningReport {
            get {
                return ResourceManager.GetString("TreatmentPlanningReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Report.
        /// </summary>
        internal static string TreatmentReportTitle {
            get {
                return ResourceManager.GetString("TreatmentReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment time.
        /// </summary>
        internal static string TreatmentTime {
            get {
                return ResourceManager.GetString("TreatmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V10 Volume (incl. PTVs).
        /// </summary>
        internal static string V10Volume {
            get {
                return ResourceManager.GetString("V10Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V12 Volume (incl. PTVs).
        /// </summary>
        internal static string V12Volume {
            get {
                return ResourceManager.GetString("V12Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOIs.
        /// </summary>
        internal static string VOIs {
            get {
                return ResourceManager.GetString("VOIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes.
        /// </summary>
        internal static string Volumes {
            get {
                return ResourceManager.GetString("Volumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Z {
            get {
                return ResourceManager.GetString("Z", resourceCulture);
            }
        }
    }
}
